name: CDK Nag Compliance Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  cdk-nag-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run CDK Synth with Nag
        run: npx cdk synth

      - name: Parse Nag Report
        id: parse-nag-report
        run: |
          # CSVファイルを見つけて解析
          NAG_CSV=$(find cdk.out -name "*NagReport.csv")

          # NotCompliantな行を抽出
          NOT_COMPLIANT_ISSUES=$(grep -v "Compliant" "$NAG_CSV" | grep -v "Suppressed" | grep -v "Rule ID,Resource ID")

          # GitHub Actions の改行エスケープ処理
          NOT_COMPLIANT_ISSUES="${NOT_COMPLIANT_ISSUES//'%'/'%25'}"
          NOT_COMPLIANT_ISSUES="${NOT_COMPLIANT_ISSUES//$'\n'/'%0A'}"
          NOT_COMPLIANT_ISSUES="${NOT_COMPLIANT_ISSUES//$'\r'/'%0D'}"

          echo "issues=$NOT_COMPLIANT_ISSUES" >> $GITHUB_OUTPUT

          # 非準拠の項目がない場合は空文字を設定
          if [ -z "$NOT_COMPLIANT_ISSUES" ]; then
            echo "no_issues=true" >> $GITHUB_OUTPUT
          fi

      - name: Create PR Comment for Non-Compliant Issues
        if: steps.parse-nag-report.outputs.issues != ''
        uses: actions/github-script@v6
        with:
          script: |
            const issues = `${{ steps.parse-nag-report.outputs.issues }}`;

            const commentBody = `### :warning: CDK Nag Compliance Issues Detected

            The following CDK Nag compliance issues were found:

            \`\`\`
            ${issues}
            \`\`\`

            Please review and address these non-compliant resources to improve security and best practices.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

      - name: Create PR Comment for Successful Compliance
        if: steps.parse-nag-report.outputs.no_issues == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const commentBody = `### :white_check_mark: CDK Nag Compliance Check Passed

            No non-compliant resources were found.

            All resources meet the CDK Nag compliance standards. Great job! :tada:`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
